// web/frontend-react/src/PricingGrid.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from './api';
import { OptionChainView } from './OptionChain';
import type {
  Engine,
  Exercise,
  GridMatrix,
  GridMeta,
  OptionChain,
  OptionType,
  Workspace,
  WsObject,
} from './types';

const ENGINES: Engine[] = ['ana', 'pde', 'mcl', 'mcl_gpu'];
const GREEK_INDICATORS = ['delta', 'gamma', 'vega', 'rho', 'theta'];
const UNDERLYING_KINDS = ['equity', 'basket', 'forex', 'rainbow', 'composite'];

//! add `months` calendar months to a YYYY-MM-DD date, clamping the day to month length.
function addMonths(iso: string, months: number): string {
  const [y, m, d] = iso.split('-').map(Number);
  const target = m - 1 + months;
  const year = y + Math.floor(target / 12);
  const month = ((target % 12) + 12) % 12;
  const lastDay = new Date(Date.UTC(year, month + 1, 0)).getUTCDate();
  const day = Math.min(d, lastDay);
  const p = (n: number, w = 2) => String(n).padStart(w, '0');
  return `${p(year, 4)}-${p(month + 1)}-${p(day)}`;
}

function parseNumbers(text: string): number[] {
  return text
    .split(/[\s,]+/)
    .map((s) => Number(s.trim()))
    .filter((n) => Number.isFinite(n));
}

//! pivot the flat (underlying, type) matrices into one option chain per underlying.
function toChains(matrices: GridMatrix[]): OptionChain[] {
  const by = new Map<string, OptionChain>();
  for (const m of matrices) {
    let c = by.get(m.underlying);
    if (!c) {
      c = { underlying: m.underlying, currency: m.currency, strikes: m.strikes, maturities: m.maturities };
      by.set(m.underlying, c);
    }
    if (m.type === 'call') c.call = m;
    else c.put = m;
  }
  return [...by.values()];
}

function fmtDuration(ms: number | undefined): string {
  if (ms == null || !Number.isFinite(ms)) return '';
  if (ms < 1) return `${Math.round(ms * 1000)} µs`;
  if (ms < 1000) return `${ms < 10 ? ms.toFixed(1) : Math.round(ms)} ms`;
  const s = ms / 1000;
  if (s < 60) return `${s < 10 ? s.toFixed(2) : s.toFixed(1)} s`;
  const min = Math.floor(s / 60);
  const rem = Math.round(s % 60);
  return rem ? `${min} min ${rem} s` : `${min} min`;
}

export function PricingGrid() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [objects, setObjects] = useState<WsObject[]>([]);

  // form state
  const [engine, setEngine] = useState<Engine>('ana');
  const [types, setTypes] = useState<OptionType[]>(['call', 'put']);
  const [exercise, setExercise] = useState<Exercise>('european');
  const [currency, setCurrency] = useState('eur');
  const [underlyings, setUnderlyings] = useState<string[]>([]);
  const [strikesText, setStrikesText] = useState('80 90 100 110 120');
  const [maturities, setMaturities] = useState<string[]>([]);
  const [includeGreeks, setIncludeGreeks] = useState(true);

  // results
  const [status, setStatus] = useState<string | null>(null);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [matrices, setMatrices] = useState<GridMatrix[]>([]);
  const [meta, setMeta] = useState<GridMeta | null>(null);
  const [activeTab, setActiveTab] = useState(0);
  const poll = useRef<ReturnType<typeof setInterval> | null>(null);

  //! load the first workspace + its objects on mount, then prepopulate defaults.
  useEffect(() => {
    (async () => {
      let list = await api.workspaces();
      if (!list.length) list = [await api.createWorkspace('Default')];
      const ws = list[0];
      setWorkspace(ws);
      setObjects(await api.objects(ws.id));
      setMaturities([1, 2, 3, 4, 5].map((m) => addMonths(ws.today, m)));
    })().catch((e) => setError(e instanceof Error ? e.message : String(e)));
    return () => {
      if (poll.current) clearInterval(poll.current);
    };
  }, []);

  const underlyingObjects = useMemo(
    () => objects.filter((o) => UNDERLYING_KINDS.includes(o.kind)),
    [objects],
  );
  const currencyNames = useMemo(
    () => objects.filter((o) => o.kind === 'currency').map((o) => o.name),
    [objects],
  );
  const chains = useMemo(() => toChains(matrices), [matrices]);

  const toggle = <T,>(arr: T[], v: T): T[] => (arr.includes(v) ? arr.filter((x) => x !== v) : [...arr, v]);

  const canSubmit =
    !!workspace && underlyings.length > 0 && types.length > 0 && parseNumbers(strikesText).length > 0 && maturities.length > 0 && !running;

  const submit = async () => {
    if (!workspace) return;
    setError(null);
    setMatrices([]);
    setMeta(null);
    setRunning(true);
    setStatus('queued');
    const indicators = ['premium', ...(includeGreeks ? GREEK_INDICATORS : [])];
    try {
      const { jobId } = await api.submitGrid({
        workspaceId: workspace.id,
        engine,
        underlyings,
        types,
        strikes: parseNumbers(strikesText),
        maturities,
        indicators,
        exercise,
        currency,
      });
      poll.current = setInterval(async () => {
        try {
          const p = await api.gridProgress(jobId);
          setStatus(p.status);
          if (p.status === 'done' || p.status === 'error') {
            if (poll.current) clearInterval(poll.current);
            const run = await api.getGrid(jobId);
            setRunning(false);
            if (run.status === 'error') setError(run.error ?? 'Pricing failed');
            else {
              setMatrices(run.result?.matrices ?? []);
              setMeta(run.result?.meta ?? null);
              setActiveTab(0);
            }
          }
        } catch (e) {
          if (poll.current) clearInterval(poll.current);
          setRunning(false);
          setError(e instanceof Error ? e.message : String(e));
        }
      }, 700);
    } catch (e) {
      setRunning(false);
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  const seed = async () => {
    if (!workspace) return;
    await api.seed(workspace.id, Math.floor(Math.random() * 1e9));
    setObjects(await api.objects(workspace.id));
  };

  return (
    <div className="grid-page">
      <h2>Pricing grid</h2>

      <div className="card form">
        <div className="row">
          <div className="field">
            <label className="lbl">Engine</label>
            <div className="toggle-group">
              {ENGINES.map((e) => (
                <button key={e} className={engine === e ? 'on' : ''} onClick={() => setEngine(e)}>
                  {e === 'mcl_gpu' ? 'mcl/gpu' : e}
                </button>
              ))}
            </div>
          </div>
          <div className="field">
            <label className="lbl">Type</label>
            <div className="checks">
              {(['call', 'put'] as OptionType[]).map((t) => (
                <label key={t}>
                  <input type="checkbox" checked={types.includes(t)} onChange={() => setTypes(toggle(types, t))} /> {t}
                </label>
              ))}
            </div>
          </div>
          <div className="field">
            <label className="lbl">Exercise</label>
            <div className="toggle-group">
              {(['european', 'american'] as Exercise[]).map((x) => (
                <button key={x} className={exercise === x ? 'on' : ''} onClick={() => setExercise(x)}>
                  {x}
                </button>
              ))}
            </div>
          </div>
          <div className="field">
            <label className="lbl">Currency</label>
            <select value={currency} onChange={(e) => setCurrency(e.target.value)}>
              {(currencyNames.length ? currencyNames : [currency]).map((c) => (
                <option key={c} value={c}>
                  {c}
                </option>
              ))}
            </select>
          </div>
          <label className="greeks">
            <input type="checkbox" checked={includeGreeks} onChange={(e) => setIncludeGreeks(e.target.checked)} /> Greeks
          </label>
          <span className="spacer" />
          <button className="primary" disabled={!canSubmit} onClick={submit}>
            Price grid
          </button>
        </div>

        <div className="row">
          <div className="field grow">
            <label className="lbl">Underlyings</label>
            <select
              multiple
              size={4}
              value={underlyings}
              onChange={(e) => setUnderlyings([...e.target.selectedOptions].map((o) => o.value))}
            >
              {underlyingObjects.map((o) => (
                <option key={o.name} value={o.name}>
                  {o.name} ({o.kind})
                </option>
              ))}
            </select>
            {underlyingObjects.length === 0 && (
              <button className="link" onClick={seed}>
                No underlyings — generate sample data
              </button>
            )}
          </div>
          <div className="field grow">
            <label className="lbl">Strikes</label>
            <input value={strikesText} onChange={(e) => setStrikesText(e.target.value)} placeholder="80 90 100 110 120" />
            <label className="lbl" style={{ marginTop: 8 }}>
              Maturities (YYYY-MM-DD, comma/space separated)
            </label>
            <input
              value={maturities.join(', ')}
              onChange={(e) => setMaturities(e.target.value.split(/[\s,]+/).filter(Boolean).sort())}
            />
          </div>
        </div>
      </div>

      {running && (
        <p className="muted">
          <span className="dot" /> {status}…
        </p>
      )}
      {error && <p className="error">{error}</p>}
      {meta && (
        <p className="muted small">
          Priced on <code>{meta.server}</code>
          {meta.engineMs != null && ` · engine ${fmtDuration(meta.engineMs)}`}
          {meta.execMs != null && ` · round-trip ${fmtDuration(meta.execMs)}`}
          {meta.engineVersion && ` · ${meta.engineVersion}`}
        </p>
      )}

      {chains.length > 0 && (
        <div className="results">
          <div className="tabs">
            {chains.map((c, i) => (
              <button key={c.underlying} className={i === activeTab ? 'tab on' : 'tab'} onClick={() => setActiveTab(i)}>
                {c.underlying}
              </button>
            ))}
          </div>
          {chains[activeTab] && <OptionChainView chain={chains[activeTab]} />}
        </div>
      )}
    </div>
  );
}

// web/frontend/src/app/pricing-grid/pricing-grid.component.ts
import { Component, OnDestroy, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { Subscription, interval, switchMap } from 'rxjs';
import { ApiService } from '../core/api.service';
import {
  Engine,
  GridMatrix,
  GridProgress,
  GridSubmit,
  OptionType,
  Workspace,
  WsObject,
} from '../core/models';
import { WorkspacePickerComponent } from '../shared/workspace-picker.component';
import { MatrixGridComponent } from './matrix-grid.component';

const GREEK_INDICATORS = ['delta', 'gamma', 'vega', 'rho', 'theta'];

//! Pricing-grid builder: workspace + engine (no default) + strike/maturity axes + type +
//! underlyings. For mcl the per-cell Greeks toggle is disabled (CPU MC = book-level
//! Greeks only). Submit -> POST /api/grid, poll until done, render a heatmapped grid per
//! (underlying, type).
@Component({
  selector: 'app-pricing-grid',
  standalone: true,
  imports: [
    FormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatSelectModule,
    MatInputModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule,
    MatIconModule,
    MatProgressBarModule,
    MatSnackBarModule,
    WorkspacePickerComponent,
    MatrixGridComponent,
  ],
  templateUrl: './pricing-grid.component.html',
  styleUrl: './pricing-grid.component.scss',
})
export class PricingGridComponent implements OnDestroy {
  private readonly api = inject(ApiService);
  private readonly snack = inject(MatSnackBar);
  private poll?: Subscription;

  readonly workspace = signal<Workspace | null>(null);
  readonly objects = signal<WsObject[]>([]);

  // form state
  engine: Engine | null = null;
  selectedUnderlyings: string[] = [];
  types: OptionType[] = ['call'];
  strikesText = '';
  maturitiesText = '';
  exercise: 'european' | 'american' = 'european';
  includeGreeks = true;

  readonly status = signal<string | null>(null);
  readonly progress = signal<GridProgress['progress']>(null);
  readonly running = signal(false);
  readonly matrices = signal<GridMatrix[]>([]);
  readonly error = signal<string | null>(null);

  //! Per-cell Greeks come only from ana/pde (or GPU mcl). CPU mcl -> book-level only.
  readonly mclSelected = computed(() => this.engine === 'mcl');

  // Underlying object names: kinds with an underlying-like shape. We surface any object
  // whose kind looks like an underlying (equity/basket/forex/rainbow/composite).
  readonly underlyingObjects = computed(() =>
    this.objects().filter((o) =>
      ['equity', 'basket', 'forex', 'rainbow', 'composite'].includes(o.kind),
    ),
  );

  onWorkspace(ws: Workspace): void {
    this.workspace.set(ws);
    this.selectedUnderlyings = [];
    this.matrices.set([]);
    this.api.listObjects(ws.id).subscribe((objs) => this.objects.set(objs));
  }

  setEngine(e: Engine): void {
    this.engine = e;
    if (e === 'mcl') this.includeGreeks = false;
  }

  toggleType(t: OptionType, checked: boolean): void {
    this.types = checked ? [...this.types, t] : this.types.filter((x) => x !== t);
  }

  private parseNumbers(text: string): number[] {
    return text
      .split(/[\s,]+/)
      .map((s) => s.trim())
      .filter(Boolean)
      .map(Number)
      .filter((n) => Number.isFinite(n));
  }

  private parseDates(text: string): string[] {
    return text
      .split(/[\s,]+/)
      .map((s) => s.trim())
      .filter(Boolean);
  }

  get canSubmit(): boolean {
    return (
      !!this.workspace() &&
      !!this.engine &&
      this.selectedUnderlyings.length > 0 &&
      this.types.length > 0 &&
      this.parseNumbers(this.strikesText).length > 0 &&
      this.parseDates(this.maturitiesText).length > 0 &&
      !this.running()
    );
  }

  submit(): void {
    const ws = this.workspace();
    if (!ws || !this.engine) return;

    const indicators = ['premium'];
    // per-cell Greeks only when not CPU-mcl and user opted in
    if (this.engine !== 'mcl' && this.includeGreeks) indicators.push(...GREEK_INDICATORS);

    const dto: GridSubmit = {
      workspaceId: ws.id,
      engine: this.engine,
      underlyings: this.selectedUnderlyings,
      types: this.types,
      strikes: this.parseNumbers(this.strikesText),
      maturities: this.parseDates(this.maturitiesText),
      indicators,
      exercise: this.exercise,
    };

    this.error.set(null);
    this.matrices.set([]);
    this.running.set(true);
    this.status.set('queued');

    this.api.submitGrid(dto).subscribe({
      next: ({ jobId }) => this.startPolling(jobId),
      error: (e) => this.fail(e),
    });
  }

  private startPolling(jobId: string): void {
    this.poll?.unsubscribe();
    this.poll = interval(800)
      .pipe(switchMap(() => this.api.getGridProgress(jobId)))
      .subscribe({
        next: (p) => {
          this.status.set(p.status);
          this.progress.set(p.progress);
          if (p.status === 'done' || p.status === 'error') {
            this.poll?.unsubscribe();
            this.fetchResult(jobId);
          }
        },
        error: (e) => this.fail(e),
      });
  }

  private fetchResult(jobId: string): void {
    this.api.getGrid(jobId).subscribe({
      next: (res) => {
        this.running.set(false);
        if (res.status === 'error') {
          this.error.set(res.error ?? 'Pricing failed');
        } else {
          this.matrices.set(res.result?.matrices ?? []);
          if (!this.matrices().length) {
            this.snack.open('Job done but returned no matrices', 'OK', { duration: 3000 });
          }
        }
      },
      error: (e) => this.fail(e),
    });
  }

  private fail(e: unknown): void {
    this.poll?.unsubscribe();
    this.running.set(false);
    const err = e as { error?: { message?: string } };
    this.error.set(err.error?.message ?? 'Request failed');
  }

  ngOnDestroy(): void {
    this.poll?.unsubscribe();
  }

  get progressPct(): number {
    const p = this.progress();
    if (!p || !p.total) return 0;
    return Math.round((p.current / p.total) * 100);
  }
}

<div class="pg-header">
  <app-workspace-picker (selected)="onWorkspace($event)"></app-workspace-picker>
</div>

@if (workspace()) {
  <mat-card class="pg-form">
    <mat-card-content>
      <div class="row">
        <div class="field">
          <label class="lbl">Engine</label>
          <mat-button-toggle-group [value]="engine" (change)="setEngine($event.value)">
            <mat-button-toggle value="ana">ana</mat-button-toggle>
            <mat-button-toggle value="pde">pde</mat-button-toggle>
            <mat-button-toggle value="mcl">mcl</mat-button-toggle>
          </mat-button-toggle-group>
          @if (!engine) {
            <span class="hint thoth-muted">Pick an engine to continue.</span>
          }
        </div>

        <div class="field">
          <label class="lbl">Option type</label>
          <div class="checks">
            <mat-checkbox
              [checked]="types.includes('call')"
              (change)="toggleType('call', $event.checked)"
              >Call</mat-checkbox
            >
            <mat-checkbox
              [checked]="types.includes('put')"
              (change)="toggleType('put', $event.checked)"
              >Put</mat-checkbox
            >
          </div>
        </div>

        <div class="field">
          <label class="lbl">Exercise</label>
          <mat-button-toggle-group [(value)]="exercise">
            <mat-button-toggle value="european">European</mat-button-toggle>
            <mat-button-toggle value="american">American</mat-button-toggle>
          </mat-button-toggle-group>
        </div>
      </div>

      <div class="row">
        <mat-form-field appearance="outline" class="grow">
          <mat-label>Underlyings</mat-label>
          <mat-select [(ngModel)]="selectedUnderlyings" multiple>
            @for (o of underlyingObjects(); track o.name) {
              <mat-option [value]="o.name">{{ o.name }} ({{ o.kind }})</mat-option>
            }
          </mat-select>
          @if (underlyingObjects().length === 0) {
            <mat-hint>No underlying objects in this workspace.</mat-hint>
          }
        </mat-form-field>
      </div>

      <div class="row">
        <mat-form-field appearance="outline" class="grow">
          <mat-label>Strikes (comma / space separated)</mat-label>
          <input matInput [(ngModel)]="strikesText" placeholder="90, 100, 110" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="grow">
          <mat-label>Maturities (YYYY-MM-DD)</mat-label>
          <input matInput [(ngModel)]="maturitiesText" placeholder="2026-12-31 2027-06-30" />
        </mat-form-field>
      </div>

      <div class="row greeks-row">
        <mat-checkbox [(ngModel)]="includeGreeks" [disabled]="mclSelected()">
          Per-cell Greeks
        </mat-checkbox>
        @if (mclSelected()) {
          <span class="hint thoth-muted">
            <mat-icon>info</mat-icon>
            CPU Monte-Carlo gives book-level Greeks only
          </span>
        }
      </div>
    </mat-card-content>
    <mat-card-actions align="end">
      <button mat-flat-button color="primary" [disabled]="!canSubmit" (click)="submit()">
        Price grid
      </button>
    </mat-card-actions>
  </mat-card>

  @if (running()) {
    <div class="pg-progress">
      <mat-progress-bar
        [mode]="progress() ? 'determinate' : 'indeterminate'"
        [value]="progressPct"
      ></mat-progress-bar>
      <span class="thoth-muted">
        {{ status() }}
        @if (progress(); as p) {
          — {{ p.current }} / {{ p.total }}
        }
      </span>
    </div>
  }

  @if (error()) {
    <p class="thoth-error">{{ error() }}</p>
  }

  @for (mx of matrices(); track mx.underlying + mx.type) {
    <app-matrix-grid [matrix]="mx"></app-matrix-grid>
  }
} @else {
  <p class="thoth-muted">Pick or create a workspace to begin.</p>
}
